services:
  - type: web
    name: react-static-site
    buildCommand: npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    routes:
      - type: rewrite
        source: /*
        destination: /200.html
