services:
  - type: web
    name: react-static-site
    buildCommand: npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    routes:
      - type: rewrite
        source: /works/*
        destination: /works/:splat/index.html
      - type: rewrite
        source: /experience/*
        destination: /experience/:splat/index.html
      - type: rewrite
        source: /about
        destination: /about/index.html
      - type: rewrite
        source: /search
        destination: /search/index.html
      - type: rewrite
        source: /404
        destination: /404/index.html
      - type: rewrite
        source: /*
        destination: /index.html