services:
  - type: web
    name: react-static-site
    buildCommand: npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    routes:
      - type: rewrite
        source: /*
        destination: /404.html
      - type: rewrite
        source: /works/*
        destination: /works/[slug].html
      - type: rewrite
        source: /about
        destination: /about.html
