services:
  - type: web
    name: react-static-site
    buildCommand: npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    routes:
      - type: rewrite
        source: /works/
        destination: /works/index.html
      - type: rewrite
        source: /works/*
        destination: /works/[slug].html
      - type: rewrite
        source: /experiences/
        destination: /experiences/index.html
      - type: rewrite
        source: /about/
        destination: /about/index.html
      - type: rewrite
        source: /*
        destination: /index.html
